variables:
  REPOSITORY_URI: 092029861612.dkr.ecr.us-west-2.amazonaws.com/titan-proxy-router-ui:latest
  CI_AWS_ECS_CLUSTER: titan-proxy-router
  CI_AWS_ECS_SERVICE: titan-proxy-router-ui-service
  CI_AWS_ECS_TASK_DEFINITION: titan-proxy-router-ui-task

stages:
    - build
    - deploy

before_script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION
    - eval $(aws ecr get-login --no-include-email | sed 's|https://||')

build-development:
    stage: build
    only: 
        - development
    tags:
        - dedicated
    script:
        - docker build -t titan-proxy-router-ui .
        - docker tag titan-proxy-router-ui:latest $REPOSITORY_URI
        - docker push $REPOSITORY_URI

deploy-development:
    stage: deploy
    only: 
        - development
    tags:
        - dedicated
    script:
        - echo 'aws ecs describe-task-definition --region $AWS_DEFAULT_REGION --task-definition $CI_AWS_ECS_TASK_DEFINITION' > input.json
        - echo $(cat input.json | jq '.taskDefinition.containerDefinitions[].image="'$REPOSITORY_URI'"') > input.json
        - echo $(cat input.json | jq '.taskDefinition') > input.json
        - echo $(cat input.json | jq  'del(.taskDefinitionArn)' | jq 'del(.revision)' | jq 'del(.status)' | jq 'del(.requiresAttributes)' | jq 'del(.compatibilities)') > input.json
        - aws ecs register-task-definition --region "${AWS_DEFAULT_REGION}" --cli-input-json file://input.json
        - REVISION=$(aws ecs describe-task-definition --task-definition $CI_AWS_ECS_TASK_DEFINITION --region "${AWS_DEFAULT_REGION}" | egrep "revision" | tr "/" " " | awk '{print $2}' | sed 's/"$//' | cut -d "," -f 1)
        - aws ecs update-service --region $AWS_DEFAULT_REGION --cluster $CI_AWS_ECS_CLUSTER --service $CI_AWS_ECS_SERVICE --task-definition $CI_AWS_ECS_TASK_DEFINITION:$REVISION
